# Generated by Django 4.0.5 on 2022-06-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_resources',
            field=models.FileField(blank=True, upload_to='specs'),
        ),
    ]
